VERSION_2/proyecto_version2/carro/urls.py
from django.urls import path

from .import views

app_name="carro"#evitar la colicion 

urlpatterns = [
    
    path('agregar/<int:hamburguesas_id>/', views.agregar_producto, name="agregar"),
    path('agregar_p/<int:hamburguesas_id>/', views.aumentar_producto, name="agregar_p"),
    path('eliminar/<int:hamburguesas_id>/', views.eliminar_productos, name="eliminar"),
    path('restar/<int:hamburguesas_id>/', views.restar_productos, name="restar"),
    path('limpiar/', views.limpiar_carro, name="limpiar"),

]

VERSION_2/proyecto_version2/proyecto_version2/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path,include
from core import views as core_views
from productos import views as productos_views
from acerca import views as acerca_views
from django.conf import settings 
from registration import views as registration_views
from registration import views as registration_views

urlpatterns = [
    path('admin/', admin.site.urls),
    
    #-------------------------urls de cambio de contraseña----------------------------
    path('cambiar-contrasena/', auth_views.PasswordChangeView.as_view(template_name='registration/password_change_form.html'), name='password_change'),
    path('cambiar-contrasena/done/', auth_views.PasswordChangeDoneView.as_view(template_name='registration/password_change_done.html'), name='password_change_done'),
    path('restablecer-contrasena/', auth_views.PasswordResetView.as_view(template_name='registration/password_reset_form.html'), name='password_reset'),
    path('restablecer-contrasena/done/', auth_views.PasswordResetDoneView.as_view(template_name='registration/password_reset_done.html'), name='password_reset_done'),
    path('restablecer-contrasena/confirmar/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name='registration/password_reset_confirm.html'), name='password_reset_confirm'),
    path('restablecer-contrasena/completar/', auth_views.PasswordResetCompleteView.as_view(template_name='registration/password_reset_complete.html'), name='password_reset_complete'),
    
    path ('check_email/', registration_views.check_email, name='check_email'),
    
    
     #---------------------url de sugerencias---------------------------
    
    path('sugerencia/', include('sugerencia.urls')),
    
     #-------------------urls de productos y carrito de compras----------------------------------------------------
    path('',productos_views.home,{'categoriasprod_id': 1}, name='inicio'),
    
    path('car/',core_views.car, name='car'),
    
    path('carro/', include('carro.urls')),
    
    
     #--------------------------urls de registro e inicio----------------------
    path('accounts/', include('django.contrib.auth.urls')),#IMPORTAR LA LIBRERIA PARA PODER UTILIZARLA EN EL LOGIN
    path('accounts/', include('registration.urls')),
    #-----------------------url de acerca de nosotros-----------------------
    path('acerca/',acerca_views.acerca, name='acerca'),
    
    
    #--------------------------url pedidos------------------------------
    path('pedido/', include('pedido.urls')),
]

if settings.DEBUG:
    from django.conf.urls.static import static
    urlpatterns += static(settings.MEDIA_URL, 
        document_root=settings.MEDIA_ROOT)

VERSION_2/proyecto_version2/carro/models.py
from django.db import models

# Create your models here.

VERSION_2/proyecto_version2/productos/models.py
from django.db import models

# Create your models here.
class categoriasprod(models.Model):
    title=models.CharField(max_length=50,verbose_name='Titulo')
    created=models.DateTimeField(auto_now_add=True, verbose_name='Fecha creado') #añade la hora automatica
    updated=models.DateTimeField(auto_now=True, verbose_name='Fecha Actualizado')
    
    class Meta:
        verbose_name="categoiriaProd"
        verbose_name_plural="categoriasProd"
        ordering = ["created"] 
        
    def __str__(self):
        return self.title

class hamburguesas(models.Model):
    title=models.CharField(max_length=50,verbose_name='Titulo')
    categorias=models.ForeignKey(categoriasprod, on_delete=models.CASCADE)
    image1=models.ImageField(verbose_name='Imagen1',upload_to="productos")#upload para que las imagenes guardadas se hagan en el directorio projects
    descrip=models.TextField(verbose_name="Descripcion")
    precio=models.FloatField(verbose_name='precio', null=True)
    created=models.DateTimeField(auto_now_add=True, verbose_name='Fecha creado') #añade la hora automatica
    updated=models.DateTimeField(auto_now=True, verbose_name='Fecha Actualizado')

    class Meta:
        verbose_name = "hamburguesa"
        verbose_name_plural = "hamburguesas"
        ordering = ["created"] 

    def __str__(self):
        return self.title  # <=====

VERSION_2/proyecto_version2/carro/views.py
from django.shortcuts import render
from .carro import Carro
from productos.models import hamburguesas
from django.shortcuts import redirect

# Create your views here.

def agregar_producto(request, hamburguesas_id):

    carro=Carro(request)
        
    hamburguesa=hamburguesas.objects.get(id=hamburguesas_id)
    
        
    carro.agregar(hamburguesas=hamburguesa)
    
    return redirect("inicio")

def aumentar_producto(request, hamburguesas_id):

    carro=Carro(request)
        
    hamburguesa=hamburguesas.objects.get(id=hamburguesas_id)
    
        
    carro.agregar(hamburguesas=hamburguesa)
    
    return redirect("car")

def eliminar_productos(request, hamburguesas_id):
    carro = Carro(request)
    
    hamburguesa=hamburguesas.objects.get(id=hamburguesas_id)
    
    carro.eliminar(hamburguesas=hamburguesa)
    
    return redirect("car")

def restar_productos(request, hamburguesas_id):
    carro = Carro(request)

    hamburguesa=hamburguesas.objects.get(id=hamburguesas_id)
    
    carro.restar_producto(hamburguesas=hamburguesa)
    
    return redirect("car")

def limpiar_carro(request):
    
    carro = Carro(request)
    
    carro.limpiar_carro()
    
    return redirect("car")

VERSION_2/proyecto_version2/productos/views.py
from django.shortcuts import render,redirect
from .models import categoriasprod
#from carro.carro import Carro
from productos.models import hamburguesas
from carro.carro import Carro


# Create your views here.

def home(request, categoriasprod_id): #esperar una respuesta (request)
    categorias = categoriasprod.objects.all()
    cate1 = categoriasprod.objects.get(id=1)
    cate2 = categoriasprod.objects.get(id=2)
    cate3 = categoriasprod.objects.get(id=3)
    cate5 = categoriasprod.objects.get(id=5)
    cate4 = categoriasprod.objects.get(id=4)
    cate6 = categoriasprod.objects.get(id=6)
    carro = Carro(request)
    cantidad = carro.contar_productos()
    return render(request,'productos/home.html',{'categorias':categorias,'cate1':cate1,
                'cate2':cate2,'cate3':cate3,'cate5':cate5,'cate4':cate4,'cate6':cate6,'cantidad': cantidad})

VERSION_2/proyecto_version2/productos/templates/carro/widget.html
<div class="container" id="table-car">
  
<table class="table table-striped table-hover">
  <thead>
    <tr>
      <th scope="col">Nombre Producto</th>
      <th scope="col">Cantidad</th>
      <th scope="col">Subtotal</th>
      <th scope="col">Foto</th>
      <th scope="col">Acciones</th>

    </tr>
  </thead>
  <tbody>
    {% if request.session.carro.items %}
      {% for key, value in request.session.carro.items %}
    <tr>
      <th>{{value.nombre}}</th>
   <td>
        <a href="{% url 'carro:restar' value.hamburguesas_id %}" class="boton_restar"><b>-</b></a>

        <b class="caja_cant"  id="savedQuantity">{{ value.cantidad }}</b>

        <a href="{% url 'carro:agregar_p' value.hamburguesas_id %}" class="boton_sumar"><b>+</b></a>
    </td>
    <td>$ {{value.precio|floatformat:3}} </td>
   
    <td><img src="{{value.imagen}}" alt="" width="75px"></td>

    <td>

        <a href="{% url 'carro:eliminar' value.hamburguesas_id  %}" class="boton_eliminar" ><svg xmlns="http://www.w3.org/2000/svg" width="30" height="30" fill="red" class="bi bi-x" viewBox="0 0 16 16">
          <path d="M4.646 4.646a.5.5 0 0 1 .708 0L8 7.293l2.646-2.647a.5.5 0 0 1 .708.708L8.707 8l2.647 2.646a.5.5 0 0 1-.708.708L8 8.707l-2.646 2.647a.5.5 0 0 1-.708-.708L7.293 8 4.646 5.354a.5.5 0 0 1 0-.708z"/>
        </svg></a>
    </td>
    </tr>
    
      {% endfor %}
      <tfoot>
        <td colspan="5">
          <a href="{% url 'carro:limpiar' %}" class="boton-vaciar btn btn-danger">Vaciar Carro</a>
        </td>
      </tfoot>
      {% else %}
      <tr>
          <td colspan="5">
              <div class="alert alert-danger text-center">
                  SIN PRODUCTOS
              </div>
          </td>
      </tr>
  {% endif %}
  </tbody>
</table>


  <h2 class="text-left mb-4" id="total-car">Total Carrito:</h2>
  <table class="table table-bordered" id="total-table">
    <tr>
      <td class="text-left border">Subtotal:</td>
      <td>$ {{importe_total_carro|floatformat:3}}</td>
    </tr>
    <tr>
      <td class="text-left border">Total a pagar:</td>
      <td>$ {{importe_total_carro|floatformat:3}}</td>
    </tr>
    <tr>
      <td colspan="2">
    {% if request.session.carro.items %}
      {% if request.user.is_authenticated %}
    <div class="boton-fina">
      <a href="{% url 'pedido' %}" class="btn btn-warning">Finalizar Compra</a>
    </div>
    {% endif %}
      {% endif %}
  </td>
    </tr>
  </table>
</div>

<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>

<script>



    function redirectToURL(url) {
      window.location.href = url;
    }

    $(document).ready(function() {
      // Maneja el clic en el botón de sumar
      $(document).on("click", ".boton_sumar", function(event) {
        event.preventDefault();
        var url = $(this).attr("href");
    
        // Realiza una solicitud AJAX GET a la URL
        $.get(url, function(data) {
          // Actualiza solo la parte de la tabla del carrito
          $("#table-car").html($(data).find("#table-car").html());
        });
      });
    
      // Maneja el clic en el botón de restar (puedes hacer lo mismo para eliminar)
      $(document).on("click", ".boton_restar", function(event) {
        event.preventDefault();
        var url = $(this).attr("href");
    
        // Realiza una solicitud AJAX GET a la URL
        $.get(url, function(data) {
          // Actualiza solo la parte de la tabla del carrito
          $("#table-car").html($(data).find("#table-car").html());
        });
      });

      // Maneja el clic en el botón de sumar
      $(document).on("click", ".boton_eliminar", function(event) {
        event.preventDefault();
        var url = $(this).attr("href");
    
        // Realiza una solicitud AJAX GET a la URL
        $.get(url, function(data) {
          // Actualiza solo la parte de la tabla del carrito
          $("#table-car").html($(data).find("#table-car").html());
        });
      });

      $(document).on("click", ".boton-vaciar", function(event) {
        event.preventDefault();
        var url = $(this).attr("href");
    
        // Realiza una solicitud AJAX GET a la URL
        $.get(url, function(data) {
          // Actualiza solo la parte de la tabla del carrito
          $("#table-car").html($(data).find("#table-car").html());
        });
      });
    });

    
   
  </script>

 