VERSION_2/proyecto_version2/carro/urls.py
from django.urls import path

from .import views

app_name="carro"#evitar la colicion 

urlpatterns = [
    
    path('agregar/<int:hamburguesas_id>/', views.agregar_producto, name="agregar"),
    path('agregar_p/<int:hamburguesas_id>/', views.aumentar_producto, name="agregar_p"),
    path('eliminar/<int:hamburguesas_id>/', views.eliminar_productos, name="eliminar"),
    path('restar/<int:hamburguesas_id>/', views.restar_productos, name="restar"),
    path('limpiar/', views.limpiar_carro, name="limpiar"),

]

VERSION_2/proyecto_version2/proyecto_version2/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path,include
from core import views as core_views
from productos import views as productos_views
from acerca import views as acerca_views
from django.conf import settings 
from registration import views as registration_views
from registration import views as registration_views

urlpatterns = [
    path('admin/', admin.site.urls),
    
    #-------------------------urls de cambio de contraseña----------------------------
    path('cambiar-contrasena/', auth_views.PasswordChangeView.as_view(template_name='registration/password_change_form.html'), name='password_change'),
    path('cambiar-contrasena/done/', auth_views.PasswordChangeDoneView.as_view(template_name='registration/password_change_done.html'), name='password_change_done'),
    path('restablecer-contrasena/', auth_views.PasswordResetView.as_view(template_name='registration/password_reset_form.html'), name='password_reset'),
    path('restablecer-contrasena/done/', auth_views.PasswordResetDoneView.as_view(template_name='registration/password_reset_done.html'), name='password_reset_done'),
    path('restablecer-contrasena/confirmar/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name='registration/password_reset_confirm.html'), name='password_reset_confirm'),
    path('restablecer-contrasena/completar/', auth_views.PasswordResetCompleteView.as_view(template_name='registration/password_reset_complete.html'), name='password_reset_complete'),
    
    path ('check_email/', registration_views.check_email, name='check_email'),
    
    
     #---------------------url de sugerencias---------------------------
    
    path('sugerencia/', include('sugerencia.urls')),
    
     #-------------------urls de productos y carrito de compras----------------------------------------------------
    path('',productos_views.home,{'categoriasprod_id': 1}, name='inicio'),
    
    path('car/',core_views.car, name='car'),
    
    path('carro/', include('carro.urls')),
    
    
     #--------------------------urls de registro e inicio----------------------
    path('accounts/', include('django.contrib.auth.urls')),#IMPORTAR LA LIBRERIA PARA PODER UTILIZARLA EN EL LOGIN
    path('accounts/', include('registration.urls')),
    #-----------------------url de acerca de nosotros-----------------------
    path('acerca/',acerca_views.acerca, name='acerca'),
    
    
    #--------------------------url pedidos------------------------------
    path('pedido/', include('pedido.urls')),
]

if settings.DEBUG:
    from django.conf.urls.static import static
    urlpatterns += static(settings.MEDIA_URL, 
        document_root=settings.MEDIA_ROOT)

VERSION_2/proyecto_version2/productos/models.py
from django.db import models

# Create your models here.
class categoriasprod(models.Model):
    title=models.CharField(max_length=50,verbose_name='Titulo')
    created=models.DateTimeField(auto_now_add=True, verbose_name='Fecha creado') #añade la hora automatica
    updated=models.DateTimeField(auto_now=True, verbose_name='Fecha Actualizado')
    
    class Meta:
        verbose_name="categoiriaProd"
        verbose_name_plural="categoriasProd"
        ordering = ["created"] 
        
    def __str__(self):
        return self.title

class hamburguesas(models.Model):
    title=models.CharField(max_length=50,verbose_name='Titulo')
    categorias=models.ForeignKey(categoriasprod, on_delete=models.CASCADE)
    image1=models.ImageField(verbose_name='Imagen1',upload_to="productos")#upload para que las imagenes guardadas se hagan en el directorio projects
    descrip=models.TextField(verbose_name="Descripcion")
    precio=models.FloatField(verbose_name='precio', null=True)
    created=models.DateTimeField(auto_now_add=True, verbose_name='Fecha creado') #añade la hora automatica
    updated=models.DateTimeField(auto_now=True, verbose_name='Fecha Actualizado')

    class Meta:
        verbose_name = "hamburguesa"
        verbose_name_plural = "hamburguesas"
        ordering = ["created"] 

    def __str__(self):
        return self.title  # <=====

VERSION_2/proyecto_version2/productos/views.py
from django.shortcuts import render,redirect
from .models import categoriasprod
#from carro.carro import Carro
from productos.models import hamburguesas
from carro.carro import Carro


# Create your views here.

def home(request, categoriasprod_id): #esperar una respuesta (request)
    categorias = categoriasprod.objects.all()
    cate1 = categoriasprod.objects.get(id=1)
    cate2 = categoriasprod.objects.get(id=2)
    cate3 = categoriasprod.objects.get(id=3)
    cate5 = categoriasprod.objects.get(id=5)
    cate4 = categoriasprod.objects.get(id=4)
    cate6 = categoriasprod.objects.get(id=6)
    carro = Carro(request)
    cantidad = carro.contar_productos()
    return render(request,'productos/home.html',{'categorias':categorias,'cate1':cate1,
                'cate2':cate2,'cate3':cate3,'cate5':cate5,'cate4':cate4,'cate6':cate6,'cantidad': cantidad})

VERSION_2/proyecto_version2/productos/templates/productos/home.html
{% extends 'core/base.html'%}

{% load static %}
<title>{% block title %}Mountain Burguer{% endblock %}</title>

{% block content %}

  <!-- food section -->

  <section class="food_section layout_padding-bottom">
    <div class="container" id="table-menu">
      <div class="heading_container heading_center">
        {% if 'okpedido' in request.GET %}
          <div class="alert finalizar" id="myModal">
            Su Pedido Fue Enviado Correctamente.
        </div>
      {% endif %}
        <h2 class="title-menu">
          Nuestro Menú
        </h2>
      </div>

      <ul class="filters_menu">
        <li data-filter="#"><a href="#{{cate1.id}}">HAMBURGUESAS</li></a>
        <li data-filter="#"><a href="#{{cate2.id}}">PERROS CALIENTES</li></a>
        <li data-filter="#"><a href="#{{cate3.id}}">SALCHIPAPAS</li></a>
        <li data-filter="#"><a href="#{{cate4.id}}">PICADAS</li></a>
        <li data-filter="#"><a href="#{{cate5.id}}">COSTILLAS Y ALITAS</li></a>
        <li data-filter="#"><a href="#{{cate6.id}}">PORCIONES ADICIONALES</li></a>

      </ul>
      
        <span id="cantidad-produ"><svg xmlns="http://www.w3.org/2000/svg" width="25" fill="#ffffff" class="bi bi-cart-plus" viewBox="0 0 16 20">
          <path d="M9 5.5a.5.5 0 0 0-1 0V7H6.5a.5.5 0 0 0 0 1H8v1.5a.5.5 0 0 0 1 0V8h1.5a.5.5 0 0 0 0-1H9V5.5z"/>
          <path d="M.5 1a.5.5 0 0 0 0 1h1.11l.401 1.607 1.498 7.985A.5.5 0 0 0 4 12h1a2 2 0 1 0 0 4 2 2 0 0 0 0-4h7a2 2 0 1 0 0 4 2 2 0 0 0 0-4h1a.5.5 0 0 0 .491-.408l1.5-8A.5.5 0 0 0 14.5 3H2.89l-.405-1.621A.5.5 0 0 0 2 1H.5zm3.915 10L3.102 4h10.796l-1.313 7h-8.17zM6 14a1 1 0 1 1-2 0 1 1 0 0 1 2 0zm7 0a1 1 0 1 1-2 0 1 1 0 0 1 2 0z"/>
        </svg><a href="{% url 'car' %}">Productos en tu carrito: {{ cantidad }}</a></span>
  
      {% for categoriasprod in categorias %}
        <a name="{{categoriasprod.id}}"></a>
        <h2 class="title-burger">{{categoriasprod.title}}</h2>
        <hr class="hr-menu">
              <div class="filters-content">
                <div class="row grid">
                  {% for hamburguesas in categoriasprod.hamburguesas_set.all %}
                  <div class="col-sm-6 col-lg-4 {{ categoria.nombre|lower }}">
                      <div class="box">
                        <div>
                          <div class="img-box">
                            <img src="{{ hamburguesas.image1.url }}" alt="">
                          </div>
                          <div class="detail-box">
                            <h5>{{ hamburguesas.title }}</h5>
                            <p>{{ hamburguesas.descrip }}</p>
                            <div class="options">
                              <h6>$ {{ hamburguesas.precio|floatformat:3 }}</h6>
                              <a href="{% url 'carro:agregar' hamburguesas.id %}" class="boton-agre">
                                <svg version="1.1" id="Capa_1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px" viewBox="0 0 456.029 456.029" style="enable-background:new 0 0 456.029 456.029;" xml:space="preserve">
                                  <g>
                                    <g>
                                      <path d="M345.6,338.862c-29.184,0-53.248,23.552-53.248,53.248c0,29.184,23.552,53.248,53.248,53.248
                                   c29.184,0,53.248-23.552,53.248-53.248C398.336,362.926,374.784,338.862,345.6,338.862z" />
                                    </g>
                                  </g>
                                  <g>
                                    <g>
                                      <path d="M439.296,84.91c-1.024,0-2.56-0.512-4.096-0.512H112.64l-5.12-34.304C104.448,27.566,84.992,10.67,61.952,10.67H20.48
                                   C9.216,10.67,0,19.886,0,31.15c0,11.264,9.216,20.48,20.48,20.48h41.472c2.56,0,4.608,2.048,5.12,4.608l31.744,216.064
                                   c4.096,27.136,27.648,47.616,55.296,47.616h212.992c26.624,0,49.664-18.944,55.296-45.056l33.28-166.4
                                   C457.728,97.71,450.56,86.958,439.296,84.91z" />
                                    </g>
                                  </g>
                                  <g>
                                    <g>
                                      <path d="M215.04,389.55c-1.024-28.16-24.576-50.688-52.736-50.688c-29.696,1.536-52.224,26.112-51.2,55.296
                                   c1.024,28.16,24.064,50.688,52.224,50.688h1.024C193.536,443.31,216.576,418.734,215.04,389.55z" />
                                    </g>
                                  </g>
                                  <g>
                                  </g>
                                  <g>
                                  </g>
                                  <g>
                                  </g>
                                  <g>
                                  </g>
                                  <g>
                                  </g>
                                  <g>
                                  </g>
                                  <g>
                                  </g>
                                  <g>
                                  </g>
                                  <g>
                                  </g>
                                  <g>
                                  </g>
                                  <g>
                                  </g>
                                  <g>
                                  </g>
                                  <g>
                                  </g>
                                  <g>
                                  </g>
                                  <g>
                                  </g>
                                </svg>
                              </a>
                            </div>
                          </div>
                        </div>
                      </div>
                    </div>
                    {% endfor %}
                  </div>
                </div>
                {% endfor %}
              </div>
            </section>

<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>

<script>

  $(document).ready(function() {
    // Maneja el clic en el botón de sumar
    $(document).on("click", ".boton-agre", function(event) {
      event.preventDefault();
      var url = $(this).attr("href");
  
      // Realiza una solicitud AJAX GET a la URL
      $.get(url, function(data) {
        // Actualiza solo la parte de la tabla del carrito
        $("#table-menu").html($(data).find("#table-menu").html());
      });
    });
  });


  const modal = document.getElementById("myModal");

function mostrarMensajeTemporal() {
  modal.style.display = "block";

  setTimeout(() => {
    ocultarMensaje();
  }, 3000); // Cambia 3000 a la cantidad de milisegundos que deseas (3 segundos en este caso)
}

function ocultarMensaje() {
  modal.style.display = "none";
}

// Llamamos a la función para mostrar el mensaje al cargar la página (simulando una condición de error)
mostrarMensajeTemporal();


</script>
  <!-- end food section -->
{% endblock %}



 